# Generated by Django 4.2.4 on 2023-12-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(help_text="Full Name", max_length=255)),
                ("email_address", models.EmailField(max_length=255)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="separate multiple skills with a comma",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applicant",
                        to="companies.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_applicant",
                        to="account.profile",
                    ),
                ),
            ],
            options={
                "get_latest_by": "-id",
            },
        ),
    ]
