# Generated by Django 4.2.4 on 2023-12-14 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_company_vision"),
        ("account", "0002_accountuser_agree_to_terms"),
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Applicant",
            new_name="Applicantion",
        ),
    ]
