# Generated by Django 4.2.4 on 2023-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicants", "0002_rename_applicant_applicantion"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantion",
            name="email_address",
            field=models.EmailField(default="email@test.com", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicantion",
            name="full_name",
            field=models.CharField(
                default="test", help_text="Full Name", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicantion",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicantion",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
