# Generated by Django 4.2.4 on 2023-12-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "applicants",
            "0003_applicantion_email_address_applicantion_full_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
