# Generated by Django 4.2.4 on 2023-12-14 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_company_vision"),
        ("account", "0003_profile_banner_photo"),
        ("applicants", "0004_applicantion_is_active"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Applicantion",
            new_name="Application",
        ),
    ]
