# Generated by Django 4.2.4 on 2023-12-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_banner_photo"),
        ("applicants", "0005_rename_applicantion_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"get_latest_by": "-id"},
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimony", models.TextField()),
                ("is_moderated", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_testimony",
                        to="account.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimony",
                "verbose_name_plural": "Testimonies",
            },
        ),
    ]
