# Generated by Django 4.2.4 on 2023-12-16 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applicants", "0007_application_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimony",
        ),
    ]
