# Generated by Django 4.2.4 on 2023-12-21 15:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vision",
                    models.CharField(
                        default="Digital Marketing Solutions for Tomorrow",
                        max_length=100,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/logs/"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="company/logs/"),
                ),
                ("content", tinymce.models.HTMLField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FT", "Full Time"),
                            ("PT", "Part Time"),
                            ("RM", "Remote"),
                        ],
                        default="FT",
                        max_length=2,
                    ),
                ),
                ("positions", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("min_salary", models.PositiveIntegerField(default=100)),
                ("max_salary", models.PositiveIntegerField()),
                ("content", tinymce.models.HTMLField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_job",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
