# Generated by Django 4.2.4 on 2023-12-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_company_location_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="max_salary",
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="min_salary",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[("FT", "Full Time"), ("PT", "Part Time"), ("RM", "Remote")],
                default="FT",
                max_length=2,
            ),
        ),
    ]
