# Generated by Django 4.2.4 on 2023-12-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_job_location_job_max_salary_job_min_salary_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="positions",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
