# Generated by Django 4.2.4 on 2023-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_job_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(default="backend-dev", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
