# Generated by Django 4.2.4 on 2023-12-16 15:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0003_profile_banner_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimony", ckeditor.fields.RichTextField()),
                ("is_positive", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_testimony",
                        to="account.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimony",
                "verbose_name_plural": "Testimonies",
            },
        ),
    ]
